[package]
name = "rox"
version = "0.1.0"
authors = ["Michael Jones <m.pricejones@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maplit = "*"
